Unclear markcommand ug
AY2122S1-CS2103T-W11-2/tp pull request #234
Opened 2021-11-01 14:44 UTC by Gabau

2021-11-02 09:45 UTC, mweeruien approved these changes
LGTM!

2021-11-02 12:01 UTC, fullfatwasabi requested changes
Otherwise, LGTM!

2021-11-02 12:01 UTC, fullfatwasabi commented on docs/UserGuide.md
> +  if the shift is on a 1/10/2021, a monday, with `da/2021-10-27` as input, the shift will be added to 1/10/2021.
```suggestion
* If no date input is provided, the next occurrence of that shift is assumed.
* If only one date input is provided, the next occurrence of that shift, after the provided date is unmarked. For instance,
  if the shift is on Monday 1/11/2021, with `da/2021-10-27` as the date input, the shift on 1/10/2021 would be unmarked.
```

2021-11-04 07:09 UTC, fullfatwasabi approved these changes
LGTM!

2021-11-04 07:47 UTC, merged