Fix bugs
AY2122S1-CS2103T-W11-2/tp pull request #249
Opened 2021-11-03 15:08 UTC by Tetrerox

Closes #220 #218 #186 #181 #170 #157

2021-11-03 16:54 UTC, Gabau requested changes
LGTM, one formatting error spotted.

2021-11-03 16:54 UTC, Gabau commented on src/main/java/seedu/address/logic/commands/SwapShiftCommand.java
> +            + PREFIX_DAY_SHIFT + "dayOfWeek-slotNumber "
Should be `DAYOFWEEK-SLOTNUMBER` as fields are all caps?

2021-11-04 06:02 UTC, Gabau approved these changes
LGTM

2021-11-04 07:54 UTC, mweeruien approved these changes
LGTM

2021-11-04 07:56 UTC, merged