Branch add tests
AY2122S1-CS2103T-W11-2/tp pull request #255
Opened 2021-11-04 09:57 UTC by Tetrerox

Added tests for delete and deleteShift commands.

2021-11-04 22:27 UTC, mweeruien approved these changes
LGTM!

2021-11-05 03:29 UTC, Gabau requested changes
LGTM. One question regarding the use of the getClass method. I think it is more consistent with the rest of the codebase to use instanceof instead of getClass.

2021-11-05 03:29 UTC, Gabau commented on src/main/java/seedu/address/logic/commands/DeleteShiftCommand.java
> +        if (o == null || getClass() != o.getClass()) {
I think it is better to use instanceof. I do not see a reason to use getClass?
```suggestion
        if (o == null || !(o instanceof DeleteShiftCommand)) {
```

2021-11-05 07:58 UTC, Gabau approved these changes
LGTM

2021-11-05 08:01 UTC, merged