Surya's UserGuide.md part
AY2122S1-CS2103T-W11-2/tp pull request #34
Opened 2021-09-25 09:45 UTC by Tetrerox

closes #30

2021-09-25 12:43 UTC, Gabau approved these changes
LGTM.

2021-09-27 08:08 UTC, mweeruien commented
LGMT too!

2021-09-27 14:03 UTC, mweeruien approved these changes
LGTM !

2021-09-27 14:06 UTC, Gabau requested changes
Missing apostrophe.

2021-09-27 14:06 UTC, Gabau commented on docs/UserGuide.md
>  ### Locating persons by name: `find
Missing apostrophe.

2021-09-27 14:09 UTC, Gabau approved these changes
LGTM.

2021-09-27 14:10 UTC, merged