Update UI
AY2122S1-CS2103T-W11-2/tp pull request #40
Opened 2021-10-01 13:30 UTC by IrvingHe000

close #39

2021-10-01 13:39 UTC, fullfatwasabi approved these changes
LGTM!

2021-10-02 08:38 UTC, Gabau requested changes
LGTM. Theres some formatting issues to address.

2021-10-02 08:38 UTC, Gabau commented on docs/index.md
> +
Extra lines?

2021-10-03 04:39 UTC, IrvingHe000 commented on docs/index.md
> +
Thank you I'll fix it :)

2021-10-03 06:41 UTC, Gabau approved these changes
LGTM

2021-10-03 09:54 UTC, merged